### ISSUE TITLE
A lot of data for complement the list

### ISSUE THREAD

**Issue by eliooses** [evbots/dex-protocols#5]
Hi there @evbots !,

First, congratulations for your work with this awesome list.

My name is Elio Osés and I´m working on inDEX, a comprehensive list of decentralized exchanges:
 
> https://github.com/distribuyed/index

This is a research of two months and it is the previous work to my future book called "Mercados Descentralizados" ("Decentralized Markets" in spanish language).

There is no similar work (unfortunately for my free time) in the entire web. At this moment i have 180 DEX enlisted and 75 more to be analyzed.

My focus is in the DEXs, but the protocols are key part too, a lot of DEX have custom protocols and I think there's a lot of work to do together. 

I promise to contribute to this list once mine ends (I want reach the number of 250 DEXs), and of course I will incorporate your material mentioning your authorship.

For the moment I will update my list linked to yours.

Send me an email to elio@netfilmx.com if you wanna talk privately.

Best regards from Buenos Aires.

**Comment by evbots** [comment]
Thanks for your help, just started reviewing your pull requests. I look forward to looking into your book when it comes out!
